### PR TITLE
Switch CI over to use Github Actions.

### PR DESCRIPTION
**Pull request by jguiditta**
Signed-off-by: Jason Guiditta <jguiditt@redhat.com>

### CODE REVIEW

**Comment by jguiditta** [comment]
Ran the actions on my repo, results here:
https://github.com/jguiditta/toolchest/actions/runs/1136814998

**Review by jpichon — APPROVED** [review]
LGTM to me, and nice to include a link to check what that looks like!

**Review by fuzzball81 — APPROVED** [review]
LGTM

**Comment by fuzzball81** [comment]
Looks like we need to modify mergify, but that can be a follow on patch.

**Comment by jguiditta** [comment]
I am pretty sure it is not automerging because I had to change mergify also.

**Pull request merged**
